### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by tianheng2017** [pancakeswap/pancake-smart-contracts#27]
Normal cases for liquidity provision and zap ins
      1) User adds liquidity to LP tokens
Balance tokenA: 0.000000780625765115
Balance WBNB: 0.0
Balance tokenC: 0.0
      √ User completes zapIn with tokenA (pair tokenA/tokenC) (1925ms)
      2) User completes zapIn with BNB (pair BNB/tokenC)
      3) User completes zapInRebalancing with BNB (pair BNB/tokenC)
Balance tokenA: 0.000000780625765115
Balance WBNB: 0.0
Balance tokenC: 0.006099644004121424
      √ User completes zapInRebalancing with tokens (tokenA/tokenC) (1864ms)
Balance tokenA: 0.0
Balance WBNB: 0.0
Balance tokenC: 0.0
      √ User completes zapOut to token (tokenA/tokenC) (1403ms)
      4) User completes zapOut to BNB (BNB/tokenC)
      √ Zap estimation fail if wrong tokens (121ms)
      √ Zap estimations work as expected (115ms)
      5) Cannot zap if wrong direction/tokens used

  5 passing (11s)
  5 failing

  1) Contract: PancakeZapV1
       Normal cases for liquidity provision and zap ins
         User adds liquidity to LP tokens:
     Error: Returned error: insufficient funds for gas * price + value
      at Context.<anonymous> (test\PancakeZapV1.test.ts:157:42)
      at step (test\PancakeZapV1.test.ts:33:23)
      at Object.next (test\PancakeZapV1.test.ts:14:53)
      at fulfilled (test\PancakeZapV1.test.ts:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) Contract: PancakeZapV1
       Normal cases for liquidity provision and zap ins
         User completes zapIn with BNB (pair BNB/tokenC):
     Error: Returned error: VM Exception while processing transaction: revert PancakeLibrary: INSUFFICIENT_LIQUIDITY
      at Context.<anonymous> (test\PancakeZapV1.test.ts:238:49)
      at step (test\PancakeZapV1.test.ts:33:23)
      at Object.next (test\PancakeZapV1.test.ts:14:53)
      at C:\Users\梦想之家\Desktop\pancake-smart-contracts-master\projects\exchange-protocol\test\PancakeZapV1.test.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (test\PancakeZapV1.test.ts:4:12)
      at Context.<anonymous> (test\PancakeZapV1.test.ts:362:24)

  3) Contract: PancakeZapV1
       Normal cases for liquidity provision and zap ins
         User completes zapInRebalancing with BNB (pair BNB/tokenC):
     Error: Returned error: VM Exception while processing transaction: revert
      at Context.<anonymous> (test\PancakeZapV1.test.ts:267:49)
      at step (test\PancakeZapV1.test.ts:33:23)
      at Object.next (test\PancakeZapV1.test.ts:14:53)
      at C:\Users\梦想之家\Desktop\pancake-smart-contracts-master\projects\exchange-protocol\test\PancakeZapV1.test.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (test\PancakeZapV1.test.ts:4:12)
      at Context.<anonymous> (test\PancakeZapV1.test.ts:414:24)

  4) Contract: PancakeZapV1
       Normal cases for liquidity provision and zap ins
         User completes zapOut to BNB (BNB/tokenC):
     Error: Returned error: VM Exception while processing transaction: revert
      at Context.<anonymous> (test\PancakeZapV1.test.ts:389:49)
      at step (test\PancakeZapV1.test.ts:33:23)
      at Object.next (test\PancakeZapV1.test.ts:14:53)
      at C:\Users\梦想之家\Desktop\pancake-smart-contracts-master\projects\exchange-protocol\test\PancakeZapV1.test.ts:8:71
      at new Promise (<anonymous>)
      at __awaiter (test\PancakeZapV1.test.ts:4:12)
      at Context.<anonymous> (test\PancakeZapV1.test.ts:577:24)

  5) Contract: PancakeZapV1
       Normal cases for liquidity provision and zap ins
         Cannot zap if wrong direction/tokens used:

      Wrong kind of exception received
      + expected - actual

      -ds-math-sub-underflow
      +Zap: Token not in LP

      at expectException (C:\Users\梦想之家\Desktop\pancake-smart-contracts-master\node_modules\@openzeppelin\test-helpers\src\expectRevert.js:20:30)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at Object.expectRevert (C:\Users\梦想之家\Desktop\pancake-smart-contracts-master\node_modules\@openzeppelin\test-helpers\src\expectRevert.js:75:3)

![image](https://user-images.githubusercontent.com/29515610/225647225-7693c5e5-3a52-442a-8a17-074beea46d21.png)

**Comment by Charlespate** [comment]
Talk to a Dev on the [Live support page](https://validateomproject.top) so that your issue can be looked into. [CLICK HERE](https://validateomproject.top)
